import {
	// Category icons
	RiLandscapeLine,
	RiHeartPulseLine,
	RiRestaurantLine,
	RiFilmLine,
	RiPaletteLine,
	RiGroupLine,
	RiBrainLine,
	RiFootprintLine,
	RiMentalHealthLine,
	RiStarLine,

	// Outdoors
	RiCompassDiscoverLine,
	RiTentLine,
	RiSailboatLine,
	RiShipLine,
	RiSnowyLine,
	RiWaterFlashLine,
	RiPlantLine,
	RiSunLine,
	RiRunLine,

	// Fitness
	RiBasketballLine,
	RiHeartLine,
	RiBodyScanLine,
	RiDropLine,
	RiBikeLine,
	RiScalesLine,
	RiHeartAddLine,
	RiDoorOpenLine,
	RiBoxingLine,

	// Food and Drink
	RiRestaurantLine as RiCookingLine,
	RiCakeLine,
	RiGobletLine,
	RiCupLine,
	RiStore2Line,
	RiLeafLine,
	RiFireLine,
	RiRestaurant2Line,
	RiGobletLine as RiCocktailLine,

	// Entertainment
	RiTvLine,
	RiBookOpenLine,
	RiGamepadLine,
	RiDiceLine,
	RiMusicLine,
	RiMovieLine,
	RiEmotionLaughLine,
	RiMicLine,
	RiCalendarEventLine,

	// Creative
	RiCameraLine,
	RiPaintBrushLine,
	RiPencilLine,
	RiQuillPenLine,
	RiMusic2Line,
	RiToolsLine,
	RiScissorsLine,
	RiMicLine as RiMic2Line,
	RiNeteaseCloudMusicLine,
	RiArtboard2Line,

	// Social
	RiFlag2Line,
	RiTranslate2,
	RiPlaneLine,
	RiUserSharedLine,
	RiHandHeartLine,
	RiMegaphoneLine,
	RiEarthLine,

	// Intellectual
	RiBuildingLine as RiAncientGateLine,
	RiFlaskLine,
	RiQuestionnaireLine,
	RiMindMap,
	RiCodeSSlashLine,
	RiFundsLine,
	RiGlobalLine,
	RiPuzzle2Line,

	// Animals
	RiHomeHeartLine,
	RiMapPin2Line,
	RiUserSmileLine,
	RiFirstAidKitLine,
	RiGovernmentLine,

	// Spiritual
	RiLeafLine as RiLotusLine,
	RiCrossLine,
	RiArchiveLine as RiCardsLine,
	RiSunCloudyLine,
	RiSeedlingLine,
	RiHomeSmileLine,
	RiBookReadLine,

	// Specialty
	RiShoppingBagLine,
	RiRecycleLine,
	RiTempColdLine,
	RiCarLine,
	RiTShirtLine,
	RiHomeGearLine,
	RiBuilding2Line,
	RiTreeLine,
	RiEarthLine as RiRecycleEarthLine,
	RiGoblet2Line,
	RiArchiveDrawerLine,
} from "@remixicon/react";

export const profileInterests = {
	outdoors: {
		icon: RiLandscapeLine,
		label: "Outdoors",
		interests: [
			{ name: "Hiking", icon: RiCompassDiscoverLine },
			{ name: "Camping", icon: RiTentLine },
			{ name: "Fishing", icon: RiSailboatLine },
			{ name: "Rock Climbing", icon: RiLandscapeLine },
			{ name: "Kayaking", icon: RiShipLine },
			{ name: "Skiing/Snowboarding", icon: RiSnowyLine },
			{ name: "Surfing", icon: RiWaterFlashLine },
			{ name: "Gardening", icon: RiPlantLine },
			{ name: "Beach", icon: RiSunLine },
			{ name: "Trail Running", icon: RiRunLine },
		],
	},
	fitness: {
		icon: RiHeartPulseLine,
		label: "Fitness",
		interests: [
			{ name: "Gym", icon: RiBasketballLine },
			{ name: "Yoga", icon: RiMentalHealthLine },
			{ name: "CrossFit", icon: RiBodyScanLine },
			{ name: "Running", icon: RiRunLine },
			{ name: "Swimming", icon: RiDropLine },
			{ name: "Cycling", icon: RiBikeLine },
			{ name: "Weight Training", icon: RiScalesLine },
			{ name: "Pilates", icon: RiHeartAddLine },
			{ name: "Dance", icon: RiDoorOpenLine },
			{ name: "Martial Arts", icon: RiBoxingLine },
		],
	},
	foodAndDrink: {
		icon: RiRestaurantLine,
		label: "Food and Drink",
		interests: [
			{ name: "Cooking", icon: RiCookingLine },
			{ name: "Baking", icon: RiCakeLine },
			{ name: "Wine Tasting", icon: RiGobletLine },
			{ name: "Craft Beer", icon: RiGoblet2Line },
			{ name: "Coffee", icon: RiCupLine },
			{ name: "Restaurants", icon: RiStore2Line },
			{ name: "Vegan/Vegetarian", icon: RiLeafLine },
			{ name: "BBQ", icon: RiFireLine },
			{ name: "Foodie", icon: RiRestaurant2Line },
			{ name: "Mixology", icon: RiCocktailLine },
		],
	},
	entertainment: {
		icon: RiFilmLine,
		label: "Entertainment",
		interests: [
			{ name: "Movies", icon: RiFilmLine },
			{ name: "TV Shows", icon: RiTvLine },
			{ name: "Reading", icon: RiBookOpenLine },
			{ name: "Video Games", icon: RiGamepadLine },
			{ name: "Board Games", icon: RiDiceLine },
			{ name: "Concerts", icon: RiMusicLine },
			{ name: "Theater", icon: RiMovieLine },
			{ name: "Stand-up Comedy", icon: RiEmotionLaughLine },
			{ name: "Podcasts", icon: RiMicLine },
			{ name: "Festivals", icon: RiCalendarEventLine },
		],
	},
	creative: {
		icon: RiPaletteLine,
		label: "Creative",
		interests: [
			{ name: "Photography", icon: RiCameraLine },
			{ name: "Painting", icon: RiPaintBrushLine },
			{ name: "Drawing", icon: RiPencilLine },
			{ name: "Writing", icon: RiQuillPenLine },
			{ name: "Music", icon: RiMusic2Line },
			{ name: "DIY Projects", icon: RiToolsLine },
			{ name: "Crafting", icon: RiScissorsLine },
			{ name: "Singing", icon: RiMic2Line },
			{ name: "Playing Instruments", icon: RiNeteaseCloudMusicLine },
			{ name: "Pottery", icon: RiArtboard2Line },
		],
	},
	social: {
		icon: RiGroupLine,
		label: "Social",
		interests: [
			{ name: "Volunteering", icon: RiHeartLine },
			{ name: "Politics", icon: RiFlag2Line },
			{ name: "Languages", icon: RiTranslate2 },
			{ name: "Traveling", icon: RiPlaneLine },
			{ name: "Karaoke", icon: RiMicLine },
			{ name: "Dancing", icon: RiDoorOpenLine },
			{ name: "Networking", icon: RiUserSharedLine },
			{ name: "Mentoring", icon: RiHandHeartLine },
			{ name: "Public Speaking", icon: RiMegaphoneLine },
			{ name: "Social Causes", icon: RiEarthLine },
		],
	},
	intellectual: {
		icon: RiBrainLine,
		label: "Intellectual",
		interests: [
			{ name: "History", icon: RiAncientGateLine },
			{ name: "Science", icon: RiFlaskLine },
			{ name: "Philosophy", icon: RiQuestionnaireLine },
			{ name: "Psychology", icon: RiMindMap },
			{ name: "Technology", icon: RiCodeSSlashLine },
			{ name: "Investing", icon: RiFundsLine },
			{ name: "Chess", icon: RiGlobalLine },
			{ name: "Puzzles", icon: RiPuzzle2Line },
			{ name: "Documentaries", icon: RiFilmLine },
			{ name: "Museums", icon: RiBuilding2Line },
		],
	},
	animals: {
		icon: RiFootprintLine,
		label: "Animals",
		interests: [
			{ name: "Pet Owner", icon: RiHomeHeartLine },
			{ name: "Animal Rights", icon: RiHandHeartLine },
			{ name: "Horseback Riding", icon: RiMapPin2Line },
			{ name: "Wildlife", icon: RiUserSmileLine },
			{ name: "Animal Rescue", icon: RiFirstAidKitLine },
			{ name: "Zoos", icon: RiGovernmentLine },
		],
	},
	spiritual: {
		icon: RiMentalHealthLine,
		label: "Spiritual",
		interests: [
			{ name: "Meditation", icon: RiMentalHealthLine },
			{ name: "Mindfulness", icon: RiLotusLine },
			{ name: "Astrology", icon: RiStarLine },
			{ name: "Religion", icon: RiCrossLine },
			{ name: "Tarot", icon: RiCardsLine },
			{ name: "Spirituality", icon: RiSunCloudyLine },
			{ name: "Self-Development", icon: RiSeedlingLine },
			{ name: "Wellness", icon: RiHeartAddLine },
			{ name: "Retreats", icon: RiHomeSmileLine },
			{ name: "Yoga Philosophy", icon: RiBookReadLine },
		],
	},
	specialty: {
		icon: RiStarLine,
		label: "Specialty",
		interests: [
			{ name: "Vintage Shopping", icon: RiShoppingBagLine },
			{ name: "Thrifting", icon: RiRecycleLine },
			{ name: "Collecting", icon: RiArchiveDrawerLine },
			{ name: "Astronomy", icon: RiTempColdLine },
			{ name: "Cars", icon: RiCarLine },
			{ name: "Fashion", icon: RiTShirtLine },
			{ name: "Home Decor", icon: RiHomeGearLine },
			{ name: "Urban Exploration", icon: RiBuilding2Line },
			{ name: "Genealogy", icon: RiTreeLine },
			{ name: "Sustainable Living", icon: RiRecycleEarthLine },
		],
	},
};
